#' westMR
#'
#' westMR implements the west procedure framework for finite mixtures of
#' regression models. Parameter estimation is performed using the EM algorithm.
#'
#'
#' @param formula A formula object (e.g., y ~ x) specifying the model.
#' @param data A data.frame containing the variables in the formula.
#' @param G_max An integer (>= 2) specifying the maximum number of
#'  groups/components.
#' @param family A character string specifying the error distribution.
#'  Defaults to 'gaussian' if not provided.
#' @param task A character vector specifying which tasks to perform.
#'  Can include "variables", "effects", or both.
#' @param control A control object of class "WMRControl" generated by
#'  \code{\link{build_control}}.
#'
#' @return A list of class \code{westMR} containing the matched \code{call},
#'  the \code{formula} (coerced for binomial responses), \code{family},
#'  \code{task}, the candidate \code{G_values}, the \code{best_fit} (the fit
#'  at the BIC-optimal number of components for the final model), and,
#'  depending on \code{task}, the \code{variable_selection} and/or
#'  \code{effect_determination} results (each \code{NULL} if that task was
#'  not run).
#'
#' @export
#'
#' @examples
#' set.seed(1)
#' n <- 500
#' pi <- c(0.2, 0.3, 0.5)
#' z <- sample(1:3, n, replace = TRUE, prob = pi)
#' x1 <- rnorm(n)
#' x2 <- rnorm(n)
#' x3 <- rnorm(n)
#' x4 <- rnorm(n)
#' sigma <- c(1, 0.5, 2)
#' beta <- rbind(
#'   g1 = c(intercept = -4, x1 = -3, x2 = 1.5, x3 = 2, x4 = 0),
#'   g2 = c(intercept = 0, x1 = 1, x2 = 1.5, x3 = -1, x4 = 0),
#'   g3 = c(intercept = 4, x1 = 3, x2 = 1.5, x3 = 0.5, x4 = 0)
#' )
#' eta <- beta[z, "intercept"] + beta[z, "x1"] * x1 + beta[z, "x2"] * x2 +
#'   beta[z, "x3"] * x3 + beta[z, "x4"] * x4
#' y <- rnorm(n, mean = eta, sd = sigma[z])
#' dat <- data.frame(y = y, x1 = x1, x2 = x2, x3 = x3, x4 = x4)
#'
#' westMR(formula = y ~ x1 + x2 + x3 + x4, data = dat, G_max = 3)
#'
westMR <- function(
  formula,
  data,
  G_max = 4,
  family = c("gaussian", "poisson", "binomial"),
  task = c("both", "variables", "effects"),
  control = build_control()
) {
  family <- match.arg(family)
  task <- match.arg(task)

  collection <- checkmate::makeAssertCollection()
  # User Input Checks
  checkmate::assert_formula(formula, add = collection)
  checkmate::assert_data_frame(data, add = collection)
  if (!isTRUE(checkmate::check_int(G_max, lower = 2))) {
    collection$push(sprintf("Maximum number of Components/Groups (G_max)
                            must be >= 2 (received: %s).", G_max))
  }
  checkmate::assert_choice(family,
    choices = c("gaussian", "poisson", "binomial"),
    add = collection
  )
  checkmate::assert_subset(task,
    choices = c("both", "variables", "effects"),
    add = collection
  )
  checkmate::assert_class(control, "WMRControl", add = collection)

  if (!collection$isEmpty()) {
    err_messages <- paste0("- ", collection$getMessages(), collapse = "\n")
    stop("(westMR) Error with arguments: \n", err_messages, call. = FALSE)
  }

  if (isTRUE(control$parallel)) {
    old_plan <- future::plan(future::multisession)
    on.exit({future::plan(old_plan)}, add = TRUE)
  }

  if (family == "binomial") {
    coerced <- coerce_binomial_formula(formula, data)
    formula <- coerced$formula
    data <- coerced$data
  }

  G_values <- seq(2, G_max)
  # Create internal model
  model <- WMRModel$new(
    formula = formula,
    data = data,
    G_values = G_values,
    family = family,
    control = control
  )

  variable_selection <- NULL
  effect_determination <- NULL
  best_fit <- NULL

  if (task %in% c("both", "variables")) {
    variable_selection <- select_variables(
      model = model,
      direction = control$direction
    )
    if (control$verbose) print(variable_selection)

    final_fits <- variable_selection$final_fits
  }
  if (task %in% c("both", "effects")) {
    effect_predictors <- if (!is.null(variable_selection)) {
      variable_selection$selected
    } else {
      model$predictors
    }
    if (length(effect_predictors) > 0L) {
      effect_determination <- determine_effects(
        model = model,
        direction = control$direction,
        predictors = effect_predictors
      )
      if (control$verbose) print(effect_determination)

      final_fits <- effect_determination$final_fits
    }
  }

  best_fit <- select_best_G(final_fits, criterion = "bic")
  if (control$verbose) print(best_fit)

  out <- list(
    call = match.call(),
    formula = formula,
    family = family,
    task = task,
    G_values = G_values,
    best_fit = best_fit,
    variable_selection = variable_selection,
    effect_determination = effect_determination
  )

  class(out) <- "westMR"
  out
}
