#' westMR
#'
#' westMR implements the west procedure framework for finite mixtures of
#' regression models. Parameter estimation is performed using the EM algorithm.
#'
#'
#' @param formula A formula object (e.g., y ~ x) specifying the model.
#' @param data A data.frame containing the variables in the formula.
#' @param G_max An integer (>= 2) specifying the maximum number of
#'  groups/components.
#' @param family A character string specifying the error distribution.
#'  Defaults to 'gaussian' if not provided.
#' @param task A character vector specifying which tasks to perform.
#'  Can include "variables", "effects", or both.
#' @param control A control object of class "WMRControl" generated by
#'  \code{\link{build_control}}.
#'
#' @return TODO
#'
#' @export
#'
#' @examples
#' westMR(formula = mpg ~ cyl, data = mtcars, G_max = 2)
#'
westMR <- function(
  formula,
  data,
  G_max = 4,
  family = c("gaussian", "poisson", "binomial"),
  task = c("both", "variables", "effects"),
  control = build_control()
) {
  family <- match.arg(family)
  task <- match.arg(task)

  collection <- checkmate::makeAssertCollection()
  # User Input Checks
  checkmate::assert_formula(formula, add = collection)
  checkmate::assert_data_frame(data, add = collection)
  if (!isTRUE(checkmate::check_int(G_max, lower = 2))) {
    collection$push(sprintf("Maximum number of Components/Groups (G_max)
                            must be >= 2 (received: %s).", G_max))
  }
  checkmate::assert_choice(family,
    choices = c("gaussian", "poisson", "binomial"),
    add = collection
  )
  checkmate::assert_subset(task,
    choices = c("both", "variables", "effects"),
    add = collection
  )
  checkmate::assert_class(control, "WMRControl", add = collection)

  if (!collection$isEmpty()) {
    err_messages <- paste0("- ", collection$getMessages(), collapse = "\n")
    stop("(westMR) Error with arguments: \n", err_messages, call. = FALSE)
  }

  if (family == "binomial") {
    coerced <- coerce_binomial_formula(formula, data)
    formula <- coerced$formula
    data <- coerced$data
  }

  G_values <- seq(2, G_max)
  # Create internal model
  model <- WMRModel$new(
    formula = formula,
    data = data,
    G_values = G_values,
    family = family,
    control = control
  )

  variable_selection <- NULL
  effect_determination <- NULL
  best_fit <- NULL

  if (task %in% c("both", "variables")) {
    variable_selection <- select_variables(
      model = model,
      direction = control$direction
    )
    if (control$verbose) print(variable_selection)
    
    best_fit <- variable_selection$best_fit
  }
  if (task %in% c("both", "effects")) {
    effect_predictors <- if (!is.null(variable_selection)) {
      variable_selection$selected
    } else {
      model$predictors
    }
    if (length(effect_predictors) > 0L) {
      effect_determination <- determine_effects(
        model = model,
        direction = control$direction,
        predictors = effect_predictors
      )
      if (control$verbose) print(effect_determination)
      
      best_fit <- effect_determination$best_fit
    }
  }

  if(control$verbose) print(best_fit)
  
  out <- list(
    call = match.call(),
    formula = formula,
    family = family,
    task = task,
    G_values = G_values,
    best_fit = best_fit,
    variable_selection = variable_selection,
    effect_determination = effect_determination
  )

  class(out) <- "westMR"
  out
}
