#' westMR
#'
#' westMR implements the west procedure framework for finite mixtures of regression models.
#' Parameter estimation is performed using the EM algorithm.
#'
#'
#' @param formula A formula object (e.g., y ~ x) specifying the model.
#' @param data A data.frame containing the variables in the formula.
#' @param G_max An integer (>= 2) specifying the maximum number of groups/components.
#' @param family A character string specifying the error distribution.
#'   Defaults to 'gaussian' if not provided.
#' @param task A character vector specifying which tasks to perform.
#'   Can include "variables", "effects", or both.
#' @param control A control object of class "WMRControl" generated by
#'   \code{\link{build_control}}.
#'
#' @return Not yet implemented
#'
#' @export
#'
#' @examples
#' westMR(formula = mpg ~ cyl, data = mtcars, G_max = 2)
#'
westMR <- function(
  formula,
  data,
  G_max = 4,
  family = c("gaussian", "poisson", "binomial"),
  task = c("variables", "effects"),
  control = build_control()
) {
  family <- match.arg(family) # defaults to gaussian

  collection <- checkmate::makeAssertCollection()
  # User Input Checks
  checkmate::assert_formula(formula, add = collection)
  checkmate::assert_data_frame(data, add = collection)
  if (!isTRUE(checkmate::check_int(G_max, lower = 2))) {
    collection$push(sprintf("Maximum number of Components/Groups (G_max) must be >= 2 (received: %s).", G_max))
  }
  checkmate::assert_choice(family, choices = c("gaussian", "poisson", "binomial"), add = collection)
  checkmate::assert_subset(task, choices = c("variables", "effects"), add = collection)

  checkmate::assert_class(control, "WMRControl", add = collection)
  if (family == "gaussian" && is.null(control$sigma_floor)) {
    mf <- stats::model.frame(
      formula = formula,
      data = data,
      na.action = stats::na.fail
    )

    response <- as.numeric(stats::model.response(mf))
    control$sigma_floor <- 0.05 * stats::sd(response)
  }

  if (!collection$isEmpty()) {
    err_messages <- paste0("- ", collection$getMessages(), collapse = "\n")
    stop("(westMR) Error with arguments: \n", err_messages, call. = FALSE)
  }

  # Create internal model
  model <- WMRModel$new(
    formula = formula,
    data = data,
    G_values = 1:G_max, # seq_len(as.integer(G_max)) ??
    family = family,
    control = control
  )

  # Run Variable Selection
  if ("variables" %in% task) {
    cat("testing variables")
  }
  # Run Effect Type Determination
  if ("effects" %in% task) {
    effect_selection <- determine_effects(model, direction = control$direction)
    print(effect_selection)
  }
}
